runmode: debug
addr: :4444
name: apiserver
url: http://127.0.0.1:4444
max_ping_count: 10

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7